library IEEE;
use IEEE.STD_LOGIC_1164.ALL;


entity Convertor_decimal is
    Port ( Number : in STD_LOGIC_VECTOR(7 downto 0);
           DEC : out STD_LOGIC_VECTOR(7 downto 0));
end Convertor_decimal;

architecture Behavioral of Convertor_decimal is

begin
process(Number)
begin
    case Number is
        when x"00" =>
            DEC(3 downto 0) <= x"0";
            DEC(7 downto 4) <= x"0";
        when x"01" =>
            DEC(3 downto 0) <= x"1";
            DEC(7 downto 4) <= x"0";
        when x"02" =>
            DEC(3 downto 0) <= x"2";
            DEC(7 downto 4) <= x"0";
        when x"03" =>
            DEC(3 downto 0) <= x"3";
            DEC(7 downto 4) <= x"0";
        when x"04" =>
            DEC(3 downto 0) <= x"4";
            DEC(7 downto 4) <= x"0";
        when x"05" =>
            DEC(3 downto 0) <= x"5";
            DEC(7 downto 4) <= x"0";
        when x"06" =>
            DEC(3 downto 0) <= x"6";
            DEC(7 downto 4) <= x"0";
        when x"07" =>
            DEC(3 downto 0) <= x"7";
            DEC(7 downto 4) <= x"0";
        when x"08" =>
            DEC(3 downto 0) <= x"8";
            DEC(7 downto 4) <= x"0";
        when x"09" =>
            DEC(3 downto 0) <= x"9";
            DEC(7 downto 4) <= x"0";
        when x"0A" =>
            DEC(3 downto 0) <= x"0";
            DEC(7 downto 4) <= x"1";
        when x"0B" =>
            DEC(3 downto 0) <= x"1";
            DEC(7 downto 4) <= x"1";
        when x"0C" =>
            DEC(3 downto 0) <= x"2";
            DEC(7 downto 4) <= x"1";
        when x"0D" =>
            DEC(3 downto 0) <= x"3";
            DEC(7 downto 4) <= x"1";
        when x"0E" =>
            DEC(3 downto 0) <= x"4";
            DEC(7 downto 4) <= x"1";
        when x"0F" =>
            DEC(3 downto 0) <= x"5";
            DEC(7 downto 4) <= x"1";
        when x"10" =>
            DEC(3 downto 0) <= x"6";
            DEC(7 downto 4) <= x"1";
        when x"11" =>
            DEC(3 downto 0) <= x"7";
            DEC(7 downto 4) <= x"1";
        when x"12" =>
            DEC(3 downto 0) <= x"8";
            DEC(7 downto 4) <= x"1";
        when x"13" =>
            DEC(3 downto 0) <= x"9";
            DEC(7 downto 4) <= x"1";
        when x"14" =>
            DEC(3 downto 0) <= x"0";
            DEC(7 downto 4) <= x"2";
        when x"15" =>
            DEC(3 downto 0) <= x"1";
            DEC(7 downto 4) <= x"2";
        when x"16" =>
            DEC(3 downto 0) <= x"2";
            DEC(7 downto 4) <= x"2";
        when x"17" =>
            DEC(3 downto 0) <= x"3";
            DEC(7 downto 4) <= x"2";
        when x"18" =>
            DEC(3 downto 0) <= x"4";
            DEC(7 downto 4) <= x"2";
        when x"19" =>
            DEC(3 downto 0) <= x"5";
            DEC(7 downto 4) <= x"2";
        when x"1A" =>
            DEC(3 downto 0) <= x"6";
            DEC(7 downto 4) <= x"2";
        when x"1B" =>
            DEC(3 downto 0) <= x"7";
            DEC(7 downto 4) <= x"2";
        when x"1C" =>
            DEC(3 downto 0) <= x"8";
            DEC(7 downto 4) <= x"2";
        when x"1D" =>
            DEC(3 downto 0) <= x"9";
            DEC(7 downto 4) <= x"2";
        when x"1E" =>
            DEC(3 downto 0) <= x"0";
            DEC(7 downto 4) <= x"3";
        when x"1F" =>
            DEC(3 downto 0) <= x"1";
            DEC(7 downto 4) <= x"3";
        when x"20" =>
            DEC(3 downto 0) <= x"2";
            DEC(7 downto 4) <= x"3";
        when x"21" =>
            DEC(3 downto 0) <= x"3";
            DEC(7 downto 4) <= x"3";
        when x"22" =>
            DEC(3 downto 0) <= x"4";
            DEC(7 downto 4) <= x"3";
        when x"23" =>
            DEC(3 downto 0) <= x"5";
            DEC(7 downto 4) <= x"3";
        when x"24" =>
            DEC(3 downto 0) <= x"6";
            DEC(7 downto 4) <= x"3";
        when x"25" =>
            DEC(3 downto 0) <= x"7";
            DEC(7 downto 4) <= x"3";
        when x"26" =>
            DEC(3 downto 0) <= x"8";
            DEC(7 downto 4) <= x"3";
        when x"27" =>
            DEC(3 downto 0) <= x"9";
            DEC(7 downto 4) <= x"3";
        when x"28" =>
            DEC(3 downto 0) <= x"0";
            DEC(7 downto 4) <= x"4";
        when x"29" =>
            DEC(3 downto 0) <= x"1";
            DEC(7 downto 4) <= x"4";
        when x"2A" =>
            DEC(3 downto 0) <= x"2";
            DEC(7 downto 4) <= x"4";
        when x"2B" =>
            DEC(3 downto 0) <= x"3";
            DEC(7 downto 4) <= x"4";
        when x"2C" =>
            DEC(3 downto 0) <= x"4";
            DEC(7 downto 4) <= x"4";
        when x"2D" =>
            DEC(3 downto 0) <= x"5";
            DEC(7 downto 4) <= x"4";
        when x"2E" =>
            DEC(3 downto 0) <= x"6";
            DEC(7 downto 4) <= x"4";
        when x"2F" =>
            DEC(3 downto 0) <= x"7";
            DEC(7 downto 4) <= x"4";
        when x"30" =>
            DEC(3 downto 0) <= x"8";
            DEC(7 downto 4) <= x"4";
        when x"31" =>
            DEC(3 downto 0) <= x"9";
            DEC(7 downto 4) <= x"4";
        when x"32" =>
            DEC(3 downto 0) <= x"0";
            DEC(7 downto 4) <= x"5";
        when x"33" =>
            DEC(3 downto 0) <= x"1";
            DEC(7 downto 4) <= x"5";
        when x"34" =>
            DEC(3 downto 0) <= x"2";
            DEC(7 downto 4) <= x"5";
        when x"35" =>
            DEC(3 downto 0) <= x"3";
            DEC(7 downto 4) <= x"5";        
        when x"36" =>
            DEC(3 downto 0) <= x"4";
            DEC(7 downto 4) <= x"5";
        when x"37" =>
            DEC(3 downto 0) <= x"5";
            DEC(7 downto 4) <= x"5";
        when x"38" =>
            DEC(3 downto 0) <= x"6";
            DEC(7 downto 4) <= x"5";
        when x"39" =>
            DEC(3 downto 0) <= x"7";
            DEC(7 downto 4) <= x"5";
        when x"3A" =>
            DEC(3 downto 0) <= x"8";
            DEC(7 downto 4) <= x"5";
        when x"3B" =>
            DEC(3 downto 0) <= x"9";
            DEC(7 downto 4) <= x"5";
        when x"3C" =>
            DEC(3 downto 0) <= x"0";
            DEC(7 downto 4) <= x"6";
        when x"3D" =>
            DEC(3 downto 0) <= x"1";
            DEC(7 downto 4) <= x"6";
        when x"3E" =>
            DEC(3 downto 0) <= x"2";
            DEC(7 downto 4) <= x"6";
        when x"3F" =>
            DEC(3 downto 0) <= x"3";
            DEC(7 downto 4) <= x"6";
        when x"40" =>
            DEC(3 downto 0) <= x"4";
            DEC(7 downto 4) <= x"6";
        when x"41" =>
            DEC(3 downto 0) <= x"5";
            DEC(7 downto 4) <= x"6";
        when x"42" =>
            DEC(3 downto 0) <= x"6";
            DEC(7 downto 4) <= x"6";
        when x"43" =>
            DEC(3 downto 0) <= x"7";
            DEC(7 downto 4) <= x"6";
        when x"44" =>
            DEC(3 downto 0) <= x"8";
            DEC(7 downto 4) <= x"6";
        when x"45" =>
            DEC(3 downto 0) <= x"9";
            DEC(7 downto 4) <= x"6";
        when x"46" =>
            DEC(3 downto 0) <= x"0";
            DEC(7 downto 4) <= x"7";
        when x"47" =>
            DEC(3 downto 0) <= x"1";
            DEC(7 downto 4) <= x"7";
        when x"48" =>
            DEC(3 downto 0) <= x"2";
            DEC(7 downto 4) <= x"7";
        when x"49" =>
            DEC(3 downto 0) <= x"3";
            DEC(7 downto 4) <= x"7";
        when x"4A" =>
            DEC(3 downto 0) <= x"4";
            DEC(7 downto 4) <= x"7";
        when x"4B" =>
            DEC(3 downto 0) <= x"5";
            DEC(7 downto 4) <= x"7";
        when x"4C" =>
            DEC(3 downto 0) <= x"6";
            DEC(7 downto 4) <= x"7";
        when x"4D" =>
            DEC(3 downto 0) <= x"7";
            DEC(7 downto 4) <= x"7";
        when x"4E" =>
            DEC(3 downto 0) <= x"8";
            DEC(7 downto 4) <= x"7";
        when x"4F" =>
            DEC(3 downto 0) <= x"9";
            DEC(7 downto 4) <= x"7";
        when x"50" =>
            DEC(3 downto 0) <= x"0";
            DEC(7 downto 4) <= x"8";
        when x"51" =>
            DEC(3 downto 0) <= x"1";
            DEC(7 downto 4) <= x"8";
        when x"52" =>
            DEC(3 downto 0) <= x"2";
            DEC(7 downto 4) <= x"8";
        when x"53" =>
            DEC(3 downto 0) <= x"3";
            DEC(7 downto 4) <= x"8";
        when x"54" =>
            DEC(3 downto 0) <= x"4";
            DEC(7 downto 4) <= x"8";
        when x"55" =>
            DEC(3 downto 0) <= x"5";
            DEC(7 downto 4) <= x"8";
        when x"56" =>
            DEC(3 downto 0) <= x"6";
            DEC(7 downto 4) <= x"8";
        when x"57" =>
            DEC(3 downto 0) <= x"7";
            DEC(7 downto 4) <= x"8";
        when x"58" =>
            DEC(3 downto 0) <= x"8";
            DEC(7 downto 4) <= x"8";
        when x"59" =>
            DEC(3 downto 0) <= x"9";
            DEC(7 downto 4) <= x"8";
        when x"5A" =>
            DEC(3 downto 0) <= x"0";
            DEC(7 downto 4) <= x"9";
        when x"5B" =>
            DEC(3 downto 0) <= x"1";
            DEC(7 downto 4) <= x"9";
        when x"5C" =>
            DEC(3 downto 0) <= x"2";
            DEC(7 downto 4) <= x"9";
        when x"5D" =>
            DEC(3 downto 0) <= x"3";
            DEC(7 downto 4) <= x"9";
        when x"5E" =>
            DEC(3 downto 0) <= x"4";
            DEC(7 downto 4) <= x"9";
        when x"5F" =>
            DEC(3 downto 0) <= x"5";
            DEC(7 downto 4) <= x"9";
        when x"60" =>
            DEC(3 downto 0) <= x"6";
            DEC(7 downto 4) <= x"9";
        when x"61" =>
            DEC(3 downto 0) <= x"7";
            DEC(7 downto 4) <= x"9";
        when x"62" =>
            DEC(3 downto 0) <= x"8";
            DEC(7 downto 4) <= x"9";
        when x"63" =>
            DEC(3 downto 0) <= x"9";
            DEC(7 downto 4) <= x"9";
        when others => 
            DEC(3 downto 0) <= x"0";
            DEC(7 downto 4) <= x"0";
     end case;
end process;
end Behavioral;
